export const MOCK_SERVICES = [
  {
    _id: 'srv-1',
    title: 'DigiLocker',
    description:
      'DigiLocker is a digital locker service provided by the Ministry of Electronics and Information Technology (MeitY), Government of India. It enables Indian citizens to store and share digital versions of their important documents like Aadhaar, PAN, driving license, vehicle registration, and educational certificates.',
    shortDescription: 'Digital document wallet for storing government-issued documents securely',
    category: 'Identity',
    icon: 'FileCheck',
    websiteUrl: 'https://digilocker.gov.in',
    appUrl: 'https://play.google.com/store/apps/details?id=com.digilocker.android',
    features: [
      'Access documents anytime, anywhere',
      'Share documents digitally with government agencies',
      'eSign documents using Aadhaar authentication',
      '1GB free cloud storage',
      'Integration with 1000+ government services',
    ],
    eligibility: 'All Indian citizens with Aadhaar number',
    documents: ['Aadhaar Card', 'Mobile Number'],
    steps: [
      { title: 'Sign Up', description: 'Visit digilocker.gov.in and sign up using Aadhaar OTP' },
      { title: 'Verify Identity', description: 'Complete eKYC verification using Aadhaar' },
      { title: 'Upload Documents', description: 'Upload or pull documents from issuers' },
      { title: 'Access Anywhere', description: 'View and share documents digitally' },
    ],
    views: 1240,
  },
  {
    _id: 'srv-2',
    title: 'UMANG (Unified Mobile Application for New-age Governance)',
    description:
      'UMANG provides access to over 1,200 central and state government services from 200+ departments across India on a single mobile application. It supports 13 Indian languages.',
    shortDescription: 'One-stop mobile app for accessing all government services',
    category: 'Governance',
    icon: 'Smartphone',
    websiteUrl: 'https://web.umang.gov.in',
    appUrl: 'https://play.google.com/store/apps/details?id=in.gov.umang.negd.g2c',
    features: [
      'Access 1,200+ government services',
      'Available in 13 Indian languages',
      'Single sign-on for all services',
      'Track application status',
    ],
    eligibility: 'All Indian citizens',
    documents: ['Mobile Number', 'Aadhaar (optional)'],
    steps: [
      { title: 'Download App', description: 'Install UMANG from Play Store or App Store' },
      { title: 'Register', description: 'Register using mobile number and OTP' },
      { title: 'Access Services', description: 'Browse and use any government service' },
    ],
    views: 980,
  },
  {
    _id: 'srv-3',
    title: 'Aadhaar Services',
    description:
      'Aadhaar is a 12-digit unique identity number issued by UIDAI. It serves as proof of identity and address across India and enables Direct Benefit Transfer (DBT).',
    shortDescription: '12-digit unique identity number for Indian residents',
    category: 'Identity',
    icon: 'Fingerprint',
    websiteUrl: 'https://uidai.gov.in',
    appUrl: 'https://play.google.com/store/apps/details?id=in.gov.uidai.mAadhaarPlus',
    features: [
      'Proof of Identity and Address',
      'Digital Life Certificate',
      'eKYC for financial services',
      'Direct Benefit Transfer (DBT)',
    ],
    eligibility: 'All residents of India',
    documents: ['Proof of Identity', 'Proof of Address', 'Date of Birth proof'],
    steps: [
      { title: 'Book Appointment', description: 'Visit uidai.gov.in and book enrollment appointment' },
      { title: 'Visit Center', description: 'Go to Aadhaar Enrollment Center with documents' },
      { title: 'Biometric Capture', description: 'Provide photo, fingerprints, and iris scan' },
    ],
    views: 1850,
  },
  {
    _id: 'srv-4',
    title: 'PAN Card Services',
    description:
      'Permanent Account Number (PAN) is a 10-digit tax identifier issued by the Income Tax Department. Instant e-PAN is available through Aadhaar-based eKYC.',
    shortDescription: '10-digit tax identification number for financial transactions',
    category: 'Finance',
    icon: 'CreditCard',
    websiteUrl: 'https://www.incometax.gov.in',
    appUrl: '',
    features: [
      'Online PAN application',
      'Instant e-PAN through Aadhaar',
      'Link PAN with Aadhaar',
    ],
    eligibility: 'All Indian citizens and foreign nationals',
    documents: ['Aadhaar Card', 'Photograph'],
    steps: [
      { title: 'Visit Portal', description: 'Go to incometax.gov.in' },
      { title: 'Apply Online', description: 'Fill the PAN application form' },
      { title: 'Submit Documents', description: 'Upload required documents & verify' },
    ],
    views: 1420,
  },
  {
    _id: 'srv-5',
    title: 'MyGov Platform',
    description:
      'MyGov is a citizen engagement platform launched by the Government of India to promote active participation of citizens in governance and nation-building.',
    shortDescription: 'Citizen engagement platform for participatory governance',
    category: 'Governance',
    icon: 'MessageSquare',
    websiteUrl: 'https://www.mygov.in',
    appUrl: 'https://play.google.com/store/apps/details?id=in.mygov',
    features: [
      'Participate in discussions and polls',
      'Submit creative ideas and feedback',
      'Earn certificates and badges',
    ],
    eligibility: 'All Indian citizens',
    documents: ['Email ID or Mobile Number'],
    steps: [
      { title: 'Register', description: 'Sign up on mygov.in' },
      { title: 'Participate', description: 'Join discussions, polls, and competitions' },
    ],
    views: 730,
  },
  {
    _id: 'srv-6',
    title: 'e-Shram Portal',
    description:
      'e-Shram is a national database for unorganized workers providing a Universal Account Number (UAN) card and social security welfare benefits.',
    shortDescription: 'National database for unorganized workers with social security benefits',
    category: 'Employment',
    icon: 'HardHat',
    websiteUrl: 'https://eshram.gov.in',
    appUrl: '',
    features: [
      'Universal Account Number (UAN) card',
      'Accident insurance coverage',
      'Access to social security schemes',
    ],
    eligibility: 'Unorganized workers aged 16-59 years',
    documents: ['Aadhaar Card', 'Bank Account', 'Mobile Number'],
    steps: [
      { title: 'Visit Portal', description: 'Go to eshram.gov.in' },
      { title: 'Enter Aadhaar', description: 'Enter Aadhaar number and verify with OTP' },
      { title: 'Download Card', description: 'Download e-Shram card with UAN' },
    ],
    views: 1100,
  },
  {
    _id: 'srv-7',
    title: 'CoWIN Portal',
    description:
      'CoWIN is the digital platform for vaccination registration, appointment scheduling, and downloadable QR-verified vaccination certificates.',
    shortDescription: 'Vaccination registration and certificate platform',
    category: 'Health',
    icon: 'Syringe',
    websiteUrl: 'https://cowin.gov.in',
    appUrl: 'https://play.google.com/store/apps/details?id=nic.goi.aarogyasetu',
    features: [
      'Vaccine registration for citizens',
      'Download vaccination certificate',
      'International travel certificate',
    ],
    eligibility: 'All citizens',
    documents: ['Aadhaar or photo ID', 'Mobile Number'],
    steps: [
      { title: 'Register', description: 'Register on cowin.gov.in' },
      { title: 'Book Slot', description: 'Book vaccination appointment' },
    ],
    views: 890,
  },
  {
    _id: 'srv-8',
    title: 'Passport Seva',
    description:
      'Passport Seva provides online portal services for fresh passport applications, re-issue, Tatkaal passports, and appointment scheduling.',
    shortDescription: 'Online passport application and management system',
    category: 'Travel',
    icon: 'Plane',
    websiteUrl: 'https://www.passportindia.gov.in',
    appUrl: 'https://play.google.com/store/apps/details?id=in.gov.mea.psp',
    features: [
      'Online passport application',
      'Appointment scheduling',
      'Track application status',
    ],
    eligibility: 'All Indian citizens',
    documents: ['Proof of Birth', 'Address proof', 'Photo ID'],
    steps: [
      { title: 'Register', description: 'Create account on Passport Seva portal' },
      { title: 'Fill Form', description: 'Complete online application form' },
      { title: 'Book Appointment', description: 'Schedule visit to Passport Seva Kendra' },
    ],
    views: 1310,
  },
];

export const MOCK_SCHEMES = [
  {
    _id: 'sch-1',
    title: 'PM Kisan Samman Nidhi (PM-KISAN)',
    description:
      'Income support of Rs. 6,000 per year is provided to all landholding farmer families across India in three equal installments of Rs. 2,000 via Direct Benefit Transfer.',
    shortDescription: 'Direct income support of Rs. 6,000/year to farmer families',
    category: 'Farmer',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedDate: '2019-02-24',
    icon: 'Wheat',
    benefits: [
      'Rs. 6,000 per year financial support',
      'Direct Benefit Transfer to bank account',
      'No intermediaries or middlemen',
    ],
    eligibility: 'All landholding farmer families with cultivable land',
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account Details'],
    applicationProcess: 'Visit pmkisan.gov.in or nearest CSC to apply online.',
    applicationUrl: 'https://pmkisan.gov.in',
    helpline: '011-23381092',
    budget: 'Rs. 75,000 Crore',
    beneficiaries: '11 Crore+ farmers',
    views: 2100,
  },
  {
    _id: 'sch-2',
    title: 'Ayushman Bharat PM-JAY',
    description:
      'Provides health insurance coverage of Rs. 5 lakh per family per year for secondary and tertiary care hospitalization to over 12 crore poor families.',
    shortDescription: 'Health coverage of Rs. 5 lakh per family per year',
    category: 'Health',
    ministry: 'Ministry of Health and Family Welfare',
    launchedDate: '2018-09-23',
    icon: 'Heart',
    benefits: [
      'Rs. 5 lakh health insurance per family per year',
      'Cashless treatment at empanelled hospitals',
      'Pre and post hospitalization expenses covered',
    ],
    eligibility: 'Families identified in SECC 2011 database',
    documents: ['Aadhaar Card', 'Ration Card', 'Mobile Number'],
    applicationProcess: 'Check eligibility on pmjay.gov.in or visit nearest Ayushman Mitra.',
    applicationUrl: 'https://pmjay.gov.in',
    helpline: '14555',
    budget: 'Rs. 6,400 Crore',
    beneficiaries: '12 Crore+ families',
    views: 1950,
  },
  {
    _id: 'sch-3',
    title: 'Pradhan Mantri Awas Yojana (PMAY)',
    description:
      'Affordable housing scheme providing interest subsidies up to 6.5% on home loans for Economically Weaker Sections (EWS) and LIG families.',
    shortDescription: 'Housing for all with subsidized home loans',
    category: 'Housing',
    ministry: 'Ministry of Housing and Urban Affairs',
    launchedDate: '2015-06-25',
    icon: 'Home',
    benefits: [
      'Interest subsidy up to 6.5% on home loans',
      'Subsidy amount up to Rs. 2.67 lakh',
      'Mandatory female ownership preference',
    ],
    eligibility: 'EWS/LIG/MIG families not owning a pucca house in India',
    documents: ['Aadhaar Card', 'Income Certificate', 'Property Documents'],
    applicationProcess: 'Apply online at pmaymis.gov.in or through participating banks.',
    applicationUrl: 'https://pmaymis.gov.in',
    helpline: '1800-11-6163',
    budget: 'Rs. 8.31 Lakh Crore',
    beneficiaries: '3 Crore+ houses',
    views: 1640,
  },
  {
    _id: 'sch-4',
    title: 'National Pension System (NPS)',
    description:
      'Government-sponsored voluntary pension scheme designed to enable systematic savings during working life with market-linked returns.',
    shortDescription: 'Voluntary retirement savings pension scheme',
    category: 'Financial Inclusion',
    ministry: 'PFRDA',
    launchedDate: '2004-01-01',
    icon: 'PiggyBank',
    benefits: [
      'Market-linked returns on investment',
      'Tax benefits under Section 80CCD',
      'Flexible pension withdrawal options',
    ],
    eligibility: 'Indian citizens aged 18-65 years',
    documents: ['Aadhaar Card', 'PAN Card', 'Bank Cheque'],
    applicationProcess: 'Register online at enps.nsdl.com or via authorized PoP branches.',
    applicationUrl: 'https://enps.nsdl.com',
    helpline: '1800-208-8282',
    budget: 'Voluntary contributions',
    beneficiaries: '4.5 Crore+ subscribers',
    views: 1120,
  },
  {
    _id: 'sch-5',
    title: 'National Scholarship Portal (NSP)',
    description:
      'Single unified platform for students to apply for various Central and State Government scholarships from Class 1 up to PhD.',
    shortDescription: 'Single platform for all government scholarships',
    category: 'Student',
    ministry: 'Ministry of Education',
    launchedDate: '2016-07-01',
    icon: 'GraduationCap',
    benefits: [
      'Single application for multiple scholarships',
      'Direct Benefit Transfer to student bank account',
      'Real-time application status tracking',
    ],
    eligibility: 'Students meeting respective scholarship criteria',
    documents: ['Aadhaar Card', 'Educational Certificate', 'Income Certificate'],
    applicationProcess: 'Register on scholarships.gov.in and fill scholarship form.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '0120-6619540',
    budget: 'Rs. 3,000 Crore+',
    beneficiaries: '5 Crore+ students',
    views: 1780,
  },
];

export const MOCK_QUIZ = [
  {
    _id: 'q-1',
    question: 'What is the primary purpose of the Aadhaar card?',
    options: [
      'To open bank accounts only',
      'To serve as a proof of identity and address',
      'To get railway tickets only',
      'To apply for passport only',
    ],
    correctAnswer: 1,
    category: 'Digital Services',
    difficulty: 'Easy',
    explanation: 'Aadhaar serves as proof of identity and address anywhere in India.',
  },
  {
    _id: 'q-2',
    question: 'How much financial support does PM-KISAN provide per year?',
    options: ['Rs. 2,000', 'Rs. 4,000', 'Rs. 6,000', 'Rs. 10,000'],
    correctAnswer: 2,
    category: 'Welfare Schemes',
    difficulty: 'Easy',
    explanation: 'PM-KISAN provides Rs. 6,000 per year in three installments of Rs. 2,000.',
  },
  {
    _id: 'q-3',
    question: 'What is the health coverage amount under Ayushman Bharat PM-JAY?',
    options: ['Rs. 1 lakh', 'Rs. 2 lakh', 'Rs. 5 lakh', 'Rs. 10 lakh'],
    correctAnswer: 2,
    category: 'Health',
    difficulty: 'Easy',
    explanation: 'Ayushman Bharat PM-JAY provides health coverage of Rs. 5 lakh per family per year.',
  },
  {
    _id: 'q-4',
    question: 'Should you ever share your OTP or UPI PIN with someone calling as a bank manager?',
    options: [
      'Yes, if they sound official',
      'No, NEVER share OTP or PIN with anyone',
      'Yes, if they promise cash rewards',
      'Only if they ask twice',
    ],
    correctAnswer: 1,
    category: 'Cyber Safety',
    difficulty: 'Easy',
    explanation: 'Government officials and banks NEVER ask for your OTP, PIN, or password over call/SMS.',
  },
  {
    _id: 'q-5',
    question: 'Which official domain extension indicates a genuine Government of India website?',
    options: ['.com or .org', '.gov.in or .nic.in', '.online or .site', '.co.in or .net'],
    correctAnswer: 1,
    category: 'Cyber Safety',
    difficulty: 'Medium',
    explanation: 'Official Government of India web portals end strictly with .gov.in or .nic.in.',
  },
];
